name: Nightly Export

on:
  schedule:
    - cron: '1 22 * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install odfpy==1.4.1  # <-- DODAJ TĘ LINIĘ
        pip install -r requirements.txt
        python -m playwright install chromium
        playwright install-deps

    - name: Run export
      env:
        PYTHONIOENCODING: UTF-8
        IAI_USERNAME: ${{ secrets.IAI_USERNAME }}
        IAI_PASSWORD: ${{ secrets.IAI_PASSWORD }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        python main.py